services:
  # Nginx
  nginx:
    build: ./nginx
    container_name: nginx
    image: 730335229700.dkr.ecr.ap-northeast-2.amazonaws.com/carsbay:nginx
    restart: always
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
<<<<<<< HEAD
  ##########
  acme-companion:
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    env_file:
      - ./.env.staging.proxy-companion
    depends_on:
      - nginx
=======
>>>>>>> 20d61f8 (deploy-reset)

  # Django
  web:
    build: .
    container_name: django
    image: 730335229700.dkr.ecr.ap-northeast-2.amazonaws.com/carsbay:web
    command: /start-django
<<<<<<< HEAD
    environment:
      - ENV=dev
=======
>>>>>>> 20d61f8 (deploy-reset)
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    expose:
      - 8000
    depends_on:
      - redis

  # Websocket
  websocket:
    build: .
    container_name: websocket
    image: 730335229700.dkr.ecr.ap-northeast-2.amazonaws.com/carsbay:websocket
    command: daphne carsbay_project.asgi:application -b 0.0.0.0 -p 9000
<<<<<<< HEAD
    environment:
      - ENV=dev
=======
>>>>>>> 20d61f8 (deploy-reset)
    volumes:
      - .:/code
    expose:
      - 9000
    depends_on:
      - redis
  # Redis
  redis:
    image: "redis:alpine"
volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
