services:
  # Nginx
  nginx:
    build: ./nginx
    container_name: nginx
    image: 730335229700.dkr.ecr.ap-northeast-2.amazonaws.com/carsbay:nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web

  # Django
  web:
    build: .
    container_name: django
    image: 730335229700.dkr.ecr.ap-northeast-2.amazonaws.com/carsbay:web
    command: /start-django
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    expose:
      - 8000
    depends_on:
      - redis
  # Redis
  redis:
    image: "redis:alpine"
volumes:
  static_volume:
  media_volume:
