services:
  web:
    container_name: carsbay
    build: .
    # apt-get update && apt-get install -y lsb-release && apt-get clean all
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./carsbay_project/.env
    depends_on:
      - redis

    # Redis
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
