services:
  # Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html # Certbot volume for challenge files
    ports:
      - "80:80"
    depends_on:
      - web
      - websocket

  # Certbot service
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt # Certbot volume for certificates
      - /var/www/html # Certbot volume for challenge files
    command: certonly --webroot --webroot-path=/var/www/html --agree-tos --email serkimdev@gmail.com -d carsbay.one
    depends_on:
      - nginx

  # Django
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django
    command: /start-django-dev
    environment:
      - ENV=dev
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    expose:
      - 8000
    depends_on:
      - redis

  # Websocket
  websocket:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: websocket
    command: daphne carsbay_project.asgi:application -b 0.0.0.0 -p 9000
    environment:
      - ENV=dev
    volumes:
      - .:/code
    expose:
      - 9000
    depends_on:
      - redis

  # Redis
  redis:
    image: "redis:alpine"
volumes:
  static_volume:
  media_volume:
