# Generated by Django 4.2 on 2024-07-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_postimage_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['make']},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['name']},
        ),
    ]
