# Generated by Django 4.2 on 2024-07-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_brand_options_alter_carmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='make',
            field=models.CharField(max_length=128, verbose_name='make'),
        ),
    ]
