# Generated by Django 4.2 on 2024-07-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_brand_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='make',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=1024, verbose_name='Description'),
        ),
    ]
